const BlockCard = [
  {
    id: "1",
    block: "Sonepur",
    panchayatName: [
      "Amnour",
      "Baijalpur",
      "Bairiya",
      "Chaklaloo",
      "Dhanhauri",
      "Dumari",
      "Fatehpur",
      "Jhaua",
      "Khaira",
      "Koral Tola",
      "Lodipur",
      "Mukrera",
      "Nayatola",
      "Nayka Tola",
      "Paharpur",
      "Phulwariya",
      "Sitalpur",
      "Sonpur",
      "Taranpur",
      "Umanagar",
      " Walipur",
      "Yusufpur",
    ],
     Amnour: [
    <img src="/village.jpg" alt="" />,
     <img src="/images1.jpeg" alt="" />,
     <img src="/images2.webp" alt="" />,
     <img src="/images3.jpg" alt="" />,
     <img src="/images4.jpg" alt="" />,
     <img src="/images5.jpeg" alt="" />,
     <img src="/images6.jpg" alt="" />,
     <img src="/images7.jpg" alt="" />,
     <img src="/images8.jpg" alt="" />,
     <img src="/images9.webp" alt="" />,
     <img src="/images10.jpg" alt="" />,
     <img src="/images8.jpg" alt="" />,
    "Aphar",
    "Shekhpura",
    "Tarwar",
    "Paiga Mitarsan",
    "Koreya",
    "Katsa",
    "Madarpur",
    "Parsa",
    "Raipura"
  ],
  Baijalpur: [
    <img src="/images7.jpg" alt="" />,
    <img src="/village.jpg" alt="" />,
     <img src="/images1.jpeg" alt="" />,
     <img src="/images2.webp" alt="" />,
     <img src="/images3.jpg" alt="" />,
     <img src="/images4.jpg" alt="" />,
     <img src="/images5.jpeg" alt="" />,
     <img src="/images6.jpg" alt="" />,
     <img src="/images7.jpg" alt="" />,
     <img src="/images8.jpg" alt="" />,
     <img src="/images9.webp" alt="" />,
     <img src="/images10.jpg" alt="" />,
     <img src="/images8.jpg" alt="" />,
    "Kishanpur",
    "rampur",
    "rehu"
  ],
  Bairiya: [
    <img src="/village.jpg" alt="" />,
     <img src="/images1.jpeg" alt="" />,
     <img src="/images2.webp" alt="" />,
     <img src="/images3.jpg" alt="" />,
     <img src="/images4.jpg" alt="" />,
     <img src="/images5.jpeg" alt="" />,
     <img src="/images6.jpg" alt="" />,
     <img src="/images7.jpg" alt="" />,
     <img src="/images8.jpg" alt="" />,
     <img src="/images9.webp" alt="" />,
     <img src="/images10.jpg" alt="" />,
     <img src="/images8.jpg" alt="" />,
    "aam","imili"
  ],
  },
  {
    id: "2",
    block: "block2",
    panchayatName: ["haldi","dhaniya"],
    haldi: [
      <img src="/village.jpg" alt="" />,
     <img src="/images1.jpeg" alt="" />,
     <img src="/images2.webp" alt="" />,
     <img src="/images3.jpg" alt="" />,
     <img src="/images4.jpg" alt="" />,
     <img src="/images5.jpeg" alt="" />,
     <img src="/images6.jpg" alt="" />,
     <img src="/images7.jpg" alt="" />,
     <img src="/images8.jpg" alt="" />,
     <img src="/images9.webp" alt="" />,
     <img src="/images10.jpg" alt="" />,
     <img src="/images8.jpg" alt="" />,
    ],
     
  },
  {
    id: "3",
    block: "chapra",
    panchayatName : [
      "Badalu Tola",
      "Barhara Mahaji",
      "Bhairopur Nizamat",
      "Bishunpura",
      "Chirand",
      "Dumari",
      "Fakuli",
      "Jalalpur",
      "Karinga",
      "Khalpura Bala",
      "Kotawa Patti Rampur",
      "Lohari",
      "Mauna",
      "Naini",
      "Rampur Bindgawa",
     " Sadha",
     " Sherpur",
     " Tenua",
     " East Telpa",
     " Musepur",
     " Bishunpura",
     "Amnour",
     "Baijalpur",
     "Bairiya",
     "Chaklaloo",
     "Dhanhauri",
     "Dumari",
     "Fatehpur",
     "Jhaua",
     "Khaira",
     "Koral Tola",
     "Lodipur",
     "Mukrera",
     "Nayatola",
     "Nayka Tola",
     "Paharpur",
     "Phulwariya",
     "Sitalpur",
     "Sonpur",
     "Taranpur",
     "Umanagar",
     " Walipur",
     "Yusufpur",
    ],
    "Badalu Tola" :
    [
      <img src="/village.jpg" alt="" />,
      <img src="/images1.jpeg" alt="" />,
      <img src="/images2.webp" alt="" />,
      <img src="/images3.jpg" alt="" />,
      <img src="/images4.jpg" alt="" />,
      <img src="/images5.jpeg" alt="" />,
      <img src="/images6.jpg" alt="" />,
      <img src="/images7.jpg" alt="" />,
      <img src="/images8.jpg" alt="" />,
      <img src="/images9.webp" alt="" />,
      <img src="/images10.jpg" alt="" />,
      <img src="/images8.jpg" alt="" />,
      <img src="/images7.jpg" alt="" />,
    <img src="/village.jpg" alt="" />,
     <img src="/images1.jpeg" alt="" />,
     <img src="/images2.webp" alt="" />,
     <img src="/images3.jpg" alt="" />,
     <img src="/images4.jpg" alt="" />,
     <img src="/images5.jpeg" alt="" />,
     <img src="/images6.jpg" alt="" />,
     <img src="/images7.jpg" alt="" />,
     <img src="/images8.jpg" alt="" />,
     <img src="/images9.webp" alt="" />,
     <img src="/images10.jpg" alt="" />,
     <img src="/images8.jpg" alt="" />,
    ]
  },
  {
    id: "4",
    block: "block4",
  },
  {
    id: "5",
    block: "block5",
  },
  {
    id: "6",
    block: "block6",
  },
  {
    id: "7",
    block: "block7",
  },
  {
    id: "8",
    block: "block8",
  },
  {
    id: "9",
    block: "block9",
  },
  {
    id: "10",
    block: "block10",
  },
  {
    id: "11",
    block: "block11",
  },
  {
    id: "12",
    block: "block12",
  },
  {
    id: "13",
    block: "block13",
  },
  {
    id: "14",
    block: "block14",
  },
  {
    id: "15",
    block: "block15",
  },
  {
    id: "16",
    block: "block16",
  },
  {
    id: "17",
    block: "block17",
  },
  {
    id: "18",
    block: "block18",
  },
];
export default BlockCard;
