const BlockCard = [
  {
    id: "1",
    block: "Amnour",
    panchayatName: [
      "Amnour",
      "Balesara",
      "Daudpur",
      "Dumari",
      "Ghorahat",
      "Inayatpur",
      "Jaitpur",
      "Lejuar",
      "Madansath",
      "Mahmmadpur",
      "Mubarakpur",
      "Nasira",
      "Sitalpur",
      "Tajpur",
    ],
     Amnour: [    
        {
          name: "Amnour Harnarayan",
          wardNo: "1",
          image: "/images1.jpeg",
        },
        {
          name: "Dharhara Khurd",
          wardNo: 14,
          image: "/images2.webp",
        },
        {
          name: "Dhorlahi Kaithal",
          wardNo: 15,
          image: "/images3.jpg",
        },
        {
          name: "Manorpur Jhakri",
          wardNo: 15,
          image: "/images4.jpg",
        },
        {
          name: "Hussepur",
          wardNo: 14,
          image: "/images5.jpeg",
        },
        {
          name: "Rasulpur",
          wardNo: 13,
          image: "/images6.jpg",
        },
        {
          name: "Aphar",
          wardNo: 15,
          image: "/images7.jpg",
        },
        {
          name: "Shekhpura",
          wardNo: 15,
          image: "/images8.jpg",
        },
        {
          name: "Tarwar",
          wardNo: 14,
          image: "/images9.webp",
        },
        {
          name: "Paiga Mitarsan",
          wardNo: 14,
          image: "/images10.jpg",
        },
        {
          name: "Koreya",
          wardNo: 15,
          image: "/images1.jpeg",
        },
        {
          name: "Katsa",
          wardNo: 14,
          image: "/images2.webp",
        },
        {
          name: "Madarpur",
          wardNo: 15,
          image: "/images10.jpg",
        },
        {
          name: "Parsa",
          wardNo: 15,
          image: "/images5.jpeg",
        },
  ],
  Baijalpur: [
    <img src="/images7.jpg" alt="" />,
    <img src="/village.jpg" alt="" />,
     <img src="/images1.jpeg" alt="" />,
     <img src="/images2.webp" alt="" />,
     <img src="/images3.jpg" alt="" />,
     <img src="/images4.jpg" alt="" />,
     <img src="/images5.jpeg" alt="" />,
     <img src="/images6.jpg" alt="" />,
     <img src="/images7.jpg" alt="" />,
     <img src="/images8.jpg" alt="" />,
     <img src="/images9.webp" alt="" />,
     <img src="/images10.jpg" alt="" />,
     <img src="/images8.jpg" alt="" />,
    "Kishanpur",
    "rampur",
    "rehu"
  ],
  Bairiya: [
    <img src="/village.jpg" alt="" />,
     <img src="/images1.jpeg" alt="" />,
     <img src="/images2.webp" alt="" />,
     <img src="/images3.jpg" alt="" />,
     <img src="/images4.jpg" alt="" />,
     <img src="/images5.jpeg" alt="" />,
     <img src="/images6.jpg" alt="" />,
     <img src="/images7.jpg" alt="" />,
     <img src="/images8.jpg" alt="" />,
     <img src="/images9.webp" alt="" />,
     <img src="/images10.jpg" alt="" />,
     <img src="/images8.jpg" alt="" />,
    "aam","imili"
  ],
  },
  {
    id: "2",
    block: "Baniyapur",
    panchayatName: [
      "Baniyapur",
      "Bhajauna Nachap",
      "Bhalua Bujurg",
      "Cheful",
      "Gobrahi",
      "Matiyar",
      "Mahmmadpur",
      "Sitalpur",
      "Tajpur",
      "Bareja",
      "Madansath",
      "Ghorahat",
      "Dumari",
      "Jaitpur",
      "Inayatpur",
      "Nasira",
    ],
    haldi: [
      <img src="/village.jpg" alt="" />,
     <img src="/images1.jpeg" alt="" />,
     <img src="/images2.webp" alt="" />,
     <img src="/images3.jpg" alt="" />,
     <img src="/images4.jpg" alt="" />,
     <img src="/images5.jpeg" alt="" />,
     <img src="/images6.jpg" alt="" />,
     <img src="/images7.jpg" alt="" />,
     <img src="/images8.jpg" alt="" />,
     <img src="/images9.webp" alt="" />,
     <img src="/images10.jpg" alt="" />,
     <img src="/images8.jpg" alt="" />,
    ],
     
  },
  {
    id: "3",
    block: "Dariyapur",
    panchayatName : [
      "Dariyapur",
      "Hasanpura",
      "Itwa",
      "Jalal Basant",
      "Kotheya",
      "Mahamda",
      "Mahmmadpur",
      "Mithepur",
      "Motirajpur",
      "Mukimpur",
      "Narayanpur",
      "Naraw",
      "Pachpatiya",
      "Pirauna",
      "Rampur",
      "Sadhpur",
      "Sareya Ratnakar",
      "Sargatti",
      "Shripal Basant",
      "Wajitpur",
      "Dewadhi",
    ],
    "Badalu Tola" :
    [
      <img src="/village.jpg" alt="" />,
      <img src="/images1.jpeg" alt="" />,
      <img src="/images2.webp" alt="" />,
      <img src="/images3.jpg" alt="" />,
      <img src="/images4.jpg" alt="" />,
      <img src="/images5.jpeg" alt="" />,
      <img src="/images6.jpg" alt="" />,
      <img src="/images7.jpg" alt="" />,
      <img src="/images8.jpg" alt="" />,
      <img src="/images9.webp" alt="" />,
      <img src="/images10.jpg" alt="" />,
      <img src="/images8.jpg" alt="" />,
      <img src="/images7.jpg" alt="" />,
    <img src="/village.jpg" alt="" />,
     <img src="/images1.jpeg" alt="" />,
     <img src="/images2.webp" alt="" />,
     <img src="/images3.jpg" alt="" />,
     <img src="/images4.jpg" alt="" />,
     <img src="/images5.jpeg" alt="" />,
     <img src="/images6.jpg" alt="" />,
     <img src="/images7.jpg" alt="" />,
     <img src="/images8.jpg" alt="" />,
     <img src="/images9.webp" alt="" />,
     <img src="/images10.jpg" alt="" />,
     <img src="/images8.jpg" alt="" />,
    ]
  },
  {
    id: "4",
    block: "Dighwara",
    panchayatName : [
      "Lejuar",
      "Dighwara",
      "Kauru Dhauru",
      "Mubarakpur",
      "Mahmmadpur",
      "Sitalpur",
      "Nasira",
      "Bareja",
      "Tajpur",
      "Ghorahat",
      "Madansath",
      "Dumari",
      "Inayatpur",
      "Jaitpur",
      "Nasira",
    ],
  },
  {
    id: "5",
    block: "Ekma",
    panchayatName : [
      "Aamdadhi",
      "Atarsan",
      "Asahani",
      "Baliya",
      "Banpura",
      "Dewpur",
      "Chanchaura",
      "Fuchtee Kala",
      "Eksar",
      "Mane",
      "Hussepur",
      "Pachua",
      "Nawada",
      "Parsa South",
      "Parsa North",
      "Rasulpur",
      "Parsa East",
      "Rampur Bindalal",
    ],
  },
  {
    id: "6",
    block: "Garkha",
    panchayatName : [
      "Bhatgai",
      "Ferusa",
      "Dewadhi",
      "Hasanpura",
      "Garkha",
      "Jalal Basant",
      "Itwa",
      "Mahamda",
      "Kotheya",
      "Maujampur",
      "Mahmmadpur",
      "Mithepur",
      "Meerpur Juara",
      "Mukimpur",
      "Motirajpur",
      "Naraw",
      "Narayanpur",
      "Pachrour",
      "Pachpatiya",
      "Rampur",
      "Pirauna",
      "Sareya Ratnakar",
      "Sadhpur",
      "Shripal Basant",
      "Wajitpur",
      "Sargatti",
    ],
  },
  {
    id: "7",
    block: "Isuapur",
    panchayatName : [
      "Isuapur",
      "Daudpur",
      "Balesara",
      "Ghorahat",
      "Dumari",
      "Jaitpur",
      "Inayatpur",
      "Madansath",
      "Lejuar",
      "Mubarakpur",
      "Mahmmadpur",
      "Sitalpur",
      "Nasira",
      "Tajpur",
    ],
  },
  {
    id: "8",
    block: "Jalalpur",
    "panchayatName": [
    "Jalalpur",
    "Balesara",
    "Daudpur",
    "Dumari",
    "Ghorahat",
    "Inayatpur",
    "Jaitpur",
    "Lejuar",
    "Madansath",
    "Mahmmadpur",
    "Mubarakpur",
    "Nasira",
    "Sitalpur",
    "Tajpur"
  ],
  },
  {
    id: "9",
    block: "Lahladpur",
    "panchayatName": [
    "Lahladpur",
    "Balesara",
    "Daudpur",
    "Dumari",
    "Ghorahat",
    "Inayatpur",
    "Jaitpur",
    "Lejuar",
    "Madansath",
    "Mahmmadpur",
    "Mubarakpur",
    "Nasira",
    "Sitalpur",
    "Tajpur"
  ],
  },
  {
    id: "10",
    block: "Maker",
    "panchayatName": [
    "Maker",
    "Balesara",
    "Daudpur",
    "Dumari",
    "Ghorahat",
    "Inayatpur",
    "Jaitpur",
    "Lejuar",
    "Madansath",
    "Mahmmadpur",
    "Mubarakpur",
    "Nasira",
    "Sitalpur",
    "Tajpur"
  ],
  },
  {
    id: "11",
    block: "Manjhi",
    "panchayatName": [
    "Manjhi East",
    "Manjhi West",
    "Balesara",
    "Daudpur",
    "Dumari",
    "Ghorahat",
    "Inayatpur",
    "Jaitpur",
    "Lejuar",
    "Madansath",
    "Mahmmadpur",
    "Mubarakpur",
    "Nasira",
    "Sitalpur",
    "Tajpur"
  ],
  },
  {
    id: "12",
    block: "Marhaura",
    "panchayatName": [
    "Marhaura",
    "Balesara",
    "Daudpur",
    "Dumari",
    "Ghorahat",
    "Inayatpur",
    "Jaitpur",
    "Lejuar",
    "Madansath",
    "Mahmmadpur",
    "Mubarakpur",
    "Nasira",
    "Sitalpur",
    "Tajpur"
  ],
  },
  {
    id: "13",
    block: "Mashrak",
    "panchayatName": [
    "Mashrak",
    "Balesara",
    "Daudpur",
    "Dumari",
    "Ghorahat",
    "Inayatpur",
    "Jaitpur",
    "Lejuar",
    "Madansath",
    "Mahmmadpur",
    "Mubarakpur",
    "Nasira",
    "Sitalpur",
    "Tajpur"
  ],
  },
  {
    id: "14",
    block: "Nagra",
    "panchayatName": [
    "Nagra",
    "Balesara",
    "Daudpur",
    "Dumari",
    "Ghorahat",
    "Inayatpur",
    "Jaitpur",
    "Lejuar",
    "Madansath",
    "Mahmmadpur",
    "Mubarakpur",
    "Nasira",
    "Sitalpur",
    "Tajpur"
  ],
  },
  {
    id: "15",
    block: "Panapur",
    "panchayatName": [
    "Panapur",
    "Balesara",
    "Daudpur",
    "Dumari",
    "Ghorahat",
    "Inayatpur",
    "Jaitpur",
    "Lejuar",
    "Madansath",
    "Mahmmadpur",
    "Mubarakpur",
    "Nasira",
    "Sitalpur",
    "Tajpur"
  ],
  },
  {
    id: "16",
    block: "Parsa",
    "panchayatName": [
    "Parsa",
    "Anjani",
    "Anyay",
    "Bahar Marar",
    "Baligaw",
    "Banauta",
    "Bheldi",
    "Chandpura",
    "Marar",
    "Pachlakh"
  ],
  },
  {
    id: "17",
    block: "Revelganj",
    panchayatName : [
      "Aamdadhi",
      "Atarsan",
      "Asahani",
      "Baliya",
      "Banpura",
      "Dewpur",
      "Chanchaura",
      "Fuchtee Kala",
      "Eksar",
      "Mane",
      "Hussepur",
      "Pachua",
      "Nawada",
      "Parsa South",
      "Parsa North",
      "Rasulpur",
      "Parsa East",
      "Rampur Bindalal",
    ],
  },
];
export default BlockCard;